### ISSUE TITLE
Importing scTE output into Seurat

### ISSUE THREAD

**Issue by laijen000** [jphe/scTE#2]
Hello!

Thank you for this tool scTE! I was able to generate the out.csv file using scTE, but was wondering if you have advice on reading the scTE out file into Seurat for downstream analysis. 

If I try: 

so.data <- fread('../scTEout.csv')
so <- CreateSeuratObject(counts = so.data)

The data is not formatted correctly; the cell barcodes are missing and the genes are the indices. 

Thank you for your help!

**Comment by ayushbharati** [comment]
Have you tried this yet?
